<?php

namespace Database\Seeders;

use App\Models\Character;
use App\Models\CharacterRelation;
use App\Models\Ship;
use Illuminate\Database\Seeder;

class CharacterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $rawCharacters = [
  [
    "id" => 'jack-sparrow',
    "name" => 'Jack Sparrow',
    "role" => 'Captain of the Black Pearl',
    "shortLine" => 'Master of luck and deception across cursed tides.',
    "quote" => '"Why is the rum always gone?"',
    "category" => 'captains',
    "tags" => ['allies', 'legends'],
    "image" => 'assets/images/characters/captain jack sparrow.jpeg',
    "biography" => 'Jack Sparrow is a cunning pirate captain known for impossible escapes, bargains with dark forces, and a moral code hidden beneath chaos. His legend is built on risk, charm, and sheer survival.',
    "ship" => 'Black Pearl',
    "weapon" => 'Sword and flintlock pistol',
    "firstAppearance" => 'The Curse of the Black Pearl (2003)',
    "allies" => ['Will Turner', 'Elizabeth Swann', 'Gibbs'],
    "enemies" => ['Davy Jones', 'Cutler Beckett', 'Captain Salazar'],
  ],
  [
    "id" => 'will-turner',
    "name" => 'Will Turner',
    "role" => 'Blacksmith Turned Sea Warrior',
    "shortLine" => 'A loyal fighter bound by love, duty, and destiny.',
    "quote" => '"No cause is lost if there is but one fool left to fight for it."',
    "category" => 'allies',
    "tags" => ['legends'],
    "image" => 'assets/images/home/will turner.jpg',
    "biography" => 'Will Turner begins as a blacksmith but becomes one of the greatest swordsmen at sea. Driven by honor and devotion, he stands at the center of pirate fate and eventually commands the Flying Dutchman.',
    "ship" => 'Flying Dutchman',
    "weapon" => 'Master-forged sword',
    "firstAppearance" => 'The Curse of the Black Pearl (2003)',
    "allies" => ['Elizabeth Swann', 'Jack Sparrow'],
    "enemies" => ['Davy Jones', 'East India Company'],
  ],
  [
    "id" => 'elizabeth-swann',
    "name" => 'Elizabeth Swann',
    "role" => 'Pirate King of the Brethren Court',
    "shortLine" => 'Noble-born strategist who became a feared sea leader.',
    "quote" => '"I am disinclined to acquiesce to your request."',
    "category" => 'allies',
    "tags" => ['legends'],
    "image" => 'assets/images/characters/swann.png',
    "biography" => 'Elizabeth Swann transforms from governor\'s daughter into one of the strongest political minds in pirate history. She commands fleets, unites factions, and refuses to surrender her freedom.',
    "ship" => 'Empress (command in battle)',
    "weapon" => 'Rapier and command authority',
    "firstAppearance" => 'The Curse of the Black Pearl (2003)',
    "allies" => ['Will Turner', 'Captain Teague', 'Jack Sparrow'],
    "enemies" => ['Lord Beckett', 'Davy Jones'],
  ],
  [
    "id" => 'hector-barbossa',
    "name" => 'Hector Barbossa',
    "role" => 'Cursed Captain and Master Tactician',
    "shortLine" => 'A ruthless navigator with a taste for ancient power.',
    "quote" => '"The code is more what you\'d call guidelines than actual rules."',
    "category" => 'captains',
    "tags" => ['villains', 'legends'],
    "image" => 'assets/images/characters/Barbosa.jpg',
    "biography" => 'Hector Barbossa is both feared and respected as a relentless captain. From cursed immortality to royal privateering, he constantly reinvents himself through cunning, ambition, and dark wit.',
    "ship" => 'Black Pearl / Queen Anne\'s Revenge',
    "weapon" => 'Sword and flintlock',
    "firstAppearance" => 'The Curse of the Black Pearl (2003)',
    "allies" => ['Jack Sparrow (uneasy)', 'Carina Smyth'],
    "enemies" => ['Jack Sparrow', 'Blackbeard', 'Salazar'],
  ],
  [
    "id" => 'davy-jones',
    "name" => 'Davy Jones',
    "role" => 'Lord of the Flying Dutchman',
    "shortLine" => 'A broken soul ruling the abyss with terror.',
    "quote" => '"Do you fear death?"',
    "category" => 'villains',
    "tags" => ['legends'],
    "image" => 'assets/images/home/davy jones.jpeg',
    "biography" => 'Davy Jones commands the cursed Flying Dutchman and collects souls owed to the sea. Betrayed in love and transformed by grief, he becomes one of the most terrifying forces in pirate mythology.',
    "ship" => 'Flying Dutchman',
    "weapon" => 'Sword and Kraken command',
    "firstAppearance" => 'Dead Man\'s Chest (2006)',
    "allies" => ['The Kraken', 'Cutler Beckett (temporary)'],
    "enemies" => ['Jack Sparrow', 'Will Turner', 'Elizabeth Swann'],
  ],
  [
    "id" => 'blackbeard',
    "name" => 'Blackbeard',
    "role" => 'Captain of Queen Anne\'s Revenge',
    "shortLine" => 'A dark sorcerer-pirate feared by every horizon.',
    "quote" => '"Fear me... if you dare."',
    "category" => 'villains',
    "tags" => ['captains', 'legends'],
    "image" => 'assets/images/characters/Black beard.jpg',
    "biography" => 'Blackbeard is a brutal captain wrapped in superstition and black magic. His command over rigging, flames, and fear turns every encounter into a nightmare for rival crews.',
    "ship" => 'Queen Anne\'s Revenge',
    "weapon" => 'Enchanted cutlass',
    "firstAppearance" => 'On Stranger Tides (2011)',
    "allies" => ['Crew of Queen Anne\'s Revenge'],
    "enemies" => ['Jack Sparrow', 'Barbossa', 'Angelica'],
  ],
  [
    "id" => 'james-norrington',
    "name" => 'James Norrington',
    "role" => 'Commodore of the Royal Navy',
    "shortLine" => 'Duty-bound officer torn between honor and obsession.',
    "quote" => '"You are without a doubt the worst pirate I\'ve ever heard of."',
    "category" => 'allies',
    "tags" => ['legends'],
    "image" => 'assets/images/characters/norrington.jpg',
    "biography" => 'Commodore Norrington begins as a proud naval officer and ultimately walks a tragic path of redemption, rivalry, and sacrifice in the shifting war between empire and piracy.',
    "ship" => 'HMS Dauntless',
    "weapon" => 'Naval saber and pistol',
    "firstAppearance" => 'The Curse of the Black Pearl (2003)',
    "allies" => ['Elizabeth Swann', 'Will Turner'],
    "enemies" => ['Jack Sparrow', 'Davy Jones'],
  ],
  [
    "id" => 'joshamee-gibbs',
    "name" => 'Joshamee Gibbs',
    "role" => 'First Mate of the Black Pearl',
    "shortLine" => 'Superstitious survivor and loyal sea storyteller.',
    "quote" => '"Take what you can, give nothing back."',
    "category" => 'allies',
    "tags" => ['legends'],
    "image" => 'assets/images/characters/Gibbs.jpg',
    "biography" => 'Gibbs is the conscience of many pirate crews, carrying sea lore, cautionary tales, and unwavering loyalty. He survives every cursed storm with wit and rum-soaked wisdom.',
    "ship" => 'Black Pearl',
    "weapon" => 'Pistol and boarding blade',
    "firstAppearance" => 'The Curse of the Black Pearl (2003)',
    "allies" => ['Jack Sparrow', 'Barbossa'],
    "enemies" => ['Royal Navy', 'East India Company'],
  ],
  [
    "id" => 'tia-dalma',
    "name" => 'Tia Dalma (Calypso)',
    "role" => 'Sea Goddess in Mortal Form',
    "shortLine" => 'Mystic keeper of tides, bargains, and prophecy.',
    "quote" => '"Same story, different versions. All are true."',
    "category" => 'legends',
    "tags" => ['allies'],
    "image" => 'assets/images/characters/tia dalma.jpg',
    "biography" => 'Known as Tia Dalma among mortals, Calypso is the imprisoned goddess of the sea. Her choices reshape fate itself, empowering storms, monsters, and men alike.',
    "ship" => 'The Sea Itself',
    "weapon" => 'Ritual magic and prophecy',
    "firstAppearance" => 'Dead Man\'s Chest (2006)',
    "allies" => ['Will Turner', 'Barbossa', 'Pirate Lords'],
    "enemies" => ['Davy Jones', 'Brethren Court (historic)'],
  ],
  [
    "id" => 'cutler-beckett',
    "name" => 'Lord Cutler Beckett',
    "role" => 'Chairman of the East India Trading Company',
    "shortLine" => 'Cold strategist determined to end piracy forever.',
    "quote" => '"It\'s just good business."',
    "category" => 'villains',
    "tags" => ['legends'],
    "image" => 'assets/images/characters/beckett.jpg',
    "biography" => 'Beckett commands fleets, law, and economics as weapons. He seeks total control of the seas by enslaving legends and crushing freedom under corporate empire.',
    "ship" => 'HMS Endeavour',
    "weapon" => 'Political power and naval command',
    "firstAppearance" => 'Dead Man\'s Chest (2006)',
    "allies" => ['Davy Jones (coerced)', 'Royal Navy'],
    "enemies" => ['Jack Sparrow', 'Brethren Court', 'Calypso'],
  ],
  [
    "id" => 'angelica',
    "name" => 'Angelica',
    "role" => 'Daughter of Blackbeard',
    "shortLine" => 'Dangerous deceiver balancing revenge and survival.',
    "quote" => '"You haven\'t changed at all."',
    "category" => 'villains',
    "tags" => ['allies', 'legends'],
    "image" => 'assets/images/characters/angelica.jpg',
    "biography" => 'Angelica is a skilled manipulator with deep ties to Jack Sparrow and Blackbeard. Her faith, ambition, and unpredictable loyalties make her one of the deadliest players at sea.',
    "ship" => 'Queen Anne\'s Revenge',
    "weapon" => 'Swordsmanship and deception',
    "firstAppearance" => 'On Stranger Tides (2011)',
    "allies" => ['Blackbeard', 'Jack Sparrow (temporary)'],
    "enemies" => ['Barbossa', 'British forces'],
  ],
  [
    "id" => 'armando-salazar',
    "name" => 'Captain Armando Salazar',
    "role" => 'Undead Hunter of Pirates',
    "shortLine" => 'Relentless ghost captain forged by vengeance.',
    "quote" => '"Death will go straight for him."',
    "category" => 'villains',
    "tags" => ['captains', 'legends'],
    "image" => 'assets/images/characters/salazar.jpeg',
    "biography" => 'Salazar, once Spain\'s feared pirate hunter, returns from the Devil\'s Triangle with a cursed crew and one purpose: destroy Jack Sparrow and every pirate legacy.',
    "ship" => 'Silent Mary',
    "weapon" => 'Rapier and spectral command',
    "firstAppearance" => 'Dead Men Tell No Tales (2017)',
    "allies" => ['Undead Silent Mary crew'],
    "enemies" => ['Jack Sparrow', 'Henry Turner', 'Carina Smyth'],
  ],
  [
    "id" => 'henry-turner',
    "name" => 'Henry Turner',
    "role" => 'Royal Navy Sailor and Son of Legends',
    "shortLine" => 'Driven heir seeking to free his father from curse.',
    "quote" => '"I will break the curse."',
    "category" => 'allies',
    "tags" => ['legends'],
    "image" => 'assets/images/characters/Henry Turner.jpg',
    "biography" => 'Henry Turner sails to break the Dutchman\'s curse and reunite his family. Bold and stubborn, he bridges old legends with a new generation of sea-faring heroes.',
    "ship" => 'Royal Navy vessels / Black Pearl alliance',
    "weapon" => 'Naval sword',
    "firstAppearance" => 'Dead Men Tell No Tales (2017)',
    "allies" => ['Carina Smyth', 'Jack Sparrow'],
    "enemies" => ['Salazar'],
  ],
  [
    "id" => 'carina-smyth',
    "name" => 'Carina Smyth',
    "role" => 'Astronomer and Keeper of the Stars',
    "shortLine" => 'Brilliant navigator armed with science and courage.',
    "quote" => '"My diary is not a diary. It\'s an astronomical journal."',
    "category" => 'allies',
    "tags" => ['legends'],
    "image" => 'assets/images/characters/Carina Smyth.jpg',
    "biography" => 'Carina deciphers celestial secrets that lead to Poseidon\'s Trident. Rational and fearless, she stands against superstition and rewrites pirate destiny with knowledge.',
    "ship" => 'Black Pearl alliance',
    "weapon" => 'Scientific knowledge and navigation',
    "firstAppearance" => 'Dead Men Tell No Tales (2017)',
    "allies" => ['Henry Turner', 'Barbossa', 'Jack Sparrow'],
    "enemies" => ['Salazar', 'Grave robbers'],
  ],
  [
    "id" => 'sao-feng',
    "name" => 'Sao Feng',
    "role" => 'Pirate Lord of the South China Sea',
    "shortLine" => 'Power broker ruling trade, territory, and fear.',
    "quote" => '"The Brethren Court has failed us."',
    "category" => 'captains',
    "tags" => ['villains', 'legends'],
    "image" => 'assets/images/characters/Sao Feng.jpg',
    "biography" => 'Sao Feng commands one of the most powerful pirate domains in the world. Ruthless and strategic, he uses alliances as currency and power as the only truth.',
    "ship" => 'Empress',
    "weapon" => 'Curved dao sword',
    "firstAppearance" => 'At World\'s End (2007)',
    "allies" => ['Brethren Court (uneasy)', 'Elizabeth Swann (briefly)'],
    "enemies" => ['Cutler Beckett', 'Norrington'],
  ],
  [
    "id" => 'bootstrap-bill',
    "name" => 'Bootstrap Bill Turner',
    "role" => 'Cursed Sailor of the Dutchman',
    "shortLine" => 'Broken father trapped beneath Jones\' command.',
    "quote" => '"Part of the ship, part of the crew."',
    "category" => 'allies',
    "tags" => ['legends'],
    "image" => 'assets/images/characters/Bootstrap Bill Turner.jpg',
    "biography" => 'Bootstrap Bill suffers the Dutchman\'s curse while trying to protect his son and redeem past sins. His story embodies sacrifice, regret, and parental devotion.',
    "ship" => 'Flying Dutchman',
    "weapon" => 'Boarding weapons and cursed resilience',
    "firstAppearance" => 'Dead Man\'s Chest (2006)',
    "allies" => ['Will Turner'],
    "enemies" => ['Davy Jones'],
  ],
  [
    "id" => 'captain-teague',
    "name" => 'Captain Teague',
    "role" => 'Keeper of the Pirate Code',
    "shortLine" => 'Ancient authority with silent, deadly command.',
    "quote" => '"It\'s not just the code. It\'s the law."',
    "category" => 'captains',
    "tags" => ['legends', 'allies'],
    "image" => 'assets/images/characters/Captain Teague.jpg',
    "biography" => 'Captain Teague presides over pirate law with austere calm. His authority in the Brethren Court shapes the politics, justice, and rituals of pirate civilization.',
    "ship" => 'Brethren Court command',
    "weapon" => 'Pistol and Pirate Code authority',
    "firstAppearance" => 'At World\'s End (2007)',
    "allies" => ['Jack Sparrow', 'Pirate Lords'],
    "enemies" => ['East India Company'],
  ],
  [
    "id" => 'marty',
    "name" => 'Marty',
    "role" => 'Black Pearl Crew Veteran',
    "shortLine" => 'Sharp-tongued deckhand with unshakeable grit.',
    "quote" => '"The world\'s still the same. There\'s just less in it."',
    "category" => 'allies',
    "tags" => ['legends'],
    "image" => 'assets/images/characters/Marty   .jpg',
    "biography" => 'Marty is among the most recognizable Black Pearl veterans, standing through mutinies, curses, and impossible voyages with dry humor and hardened resolve.',
    "ship" => 'Black Pearl',
    "weapon" => 'Boarding axe and pistols',
    "firstAppearance" => 'The Curse of the Black Pearl (2003)',
    "allies" => ['Jack Sparrow', 'Gibbs'],
    "enemies" => ['Royal Navy', 'Mutinous rivals'],
  ],
  [
    "id" => 'pintel-ragetti',
    "name" => 'Pintel and Ragetti',
    "role" => 'Infamous Trickster Duo',
    "shortLine" => 'Chaotic crewmen surviving on nerve and luck.',
    "quote" => '"Parlay? Dammit, they have that word memorized!"',
    "category" => 'allies',
    "tags" => ['legends'],
    "image" => 'assets/images/characters/Pintel and Ragetti.jpg',
    "biography" => 'Pintel and Ragetti move between rival crews while delivering comic chaos, accidental bravery, and surprising loyalty in the deadliest moments on the seven seas.',
    "ship" => 'Black Pearl and allied ships',
    "weapon" => 'Pistols and improvised blades',
    "firstAppearance" => 'The Curse of the Black Pearl (2003)',
    "allies" => ['Jack Sparrow', 'Barbossa'],
    "enemies" => ['Royal Navy'],
  ],
  [
    "id" => 'governor-weatherby-swann',
    "name" => 'Governor Weatherby Swann',
    "role" => 'Governor of Port Royal',
    "shortLine" => 'A father caught between empire and conscience.',
    "quote" => '"This is either madness... or brilliance."',
    "category" => 'allies',
    "tags" => ['legends'],
    "image" => 'assets/images/characters/Gov_Swann.jpg',
    "biography" => 'Governor Swann represents order and civility in a world of pirates, yet his devotion to Elizabeth leads him into dangerous political and moral conflicts.',
    "ship" => 'Port Royal administration',
    "weapon" => 'Political influence',
    "firstAppearance" => 'The Curse of the Black Pearl (2003)',
    "allies" => ['Elizabeth Swann', 'Norrington'],
    "enemies" => ['Cutler Beckett', 'Pirate threats'],
  ],
  [
    "id" => 'cotton-and-parrot',
    "name" => 'Cotton and Parrot',
    "role" => 'Signalman of the Black Pearl',
    "shortLine" => 'Silent sailor whose parrot speaks for the crew.',
    "quote" => '"(Parrot) Mr. Cotton\'s parrot!"',
    "category" => 'allies',
    "tags" => ['legends'],
    "image" => 'assets/images/characters/Cotton and Parrot.jpg',
    "biography" => 'Cotton and his ever-chatty parrot are among the most iconic visuals aboard the Black Pearl, symbolizing the ragged personality and unity of pirate crews.',
    "ship" => 'Black Pearl',
    "weapon" => 'Deck rigging tools and pistols',
    "firstAppearance" => 'The Curse of the Black Pearl (2003)',
    "allies" => ['Jack Sparrow', 'Gibbs', 'Marty'],
    "enemies" => ['Royal Navy'],
  ]
];

        foreach ($rawCharacters as $data) {
            // Seed unique Ships
            if (!empty($data['ship'])) {
                Ship::firstOrCreate(
                    ['name' => $data['ship']],
                    ['description' => 'A famous vessel in the Caribbean.']
                );
            }

            // Seed Character
            $character = Character::create([
                'id' => $data['id'],
                'name' => $data['name'],
                'role' => $data['role'],
                'short_line' => $data['shortLine'],
                'quote' => $data['quote'],
                'category' => $data['category'],
                'tags' => $data['tags'],
                'image' => $data['image'],
                'biography' => $data['biography'],
                'ship_name' => $data['ship'] ?? null,
                'weapon' => $data['weapon'] ?? null,
                'first_appearance' => $data['firstAppearance'] ?? null,
            ]);

            // Seed Relations (Allies)
            if (!empty($data['allies'])) {
                foreach ($data['allies'] as $allyName) {
                    CharacterRelation::create([
                        'character_id' => $character->id,
                        'related_name' => $allyName,
                        'relation_type' => 'ally',
                    ]);
                }
            }

            // Seed Relations (Enemies)
            if (!empty($data['enemies'])) {
                foreach ($data['enemies'] as $enemyName) {
                    CharacterRelation::create([
                        'character_id' => $character->id,
                        'related_name' => $enemyName,
                        'relation_type' => 'enemy',
                    ]);
                }
            }
        }
    }
}
